import os
import sys
import math
import time
import traceback
import multiprocessing
import re 
import gc
import httpx 
from pathlib import Path
from openai import OpenAI
import subprocess
import shutil

# 强制使用 Hugging Face 国内镜像源
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
# ⚠️ 注意：此处已移除全局导入 faster_whisper，以防止主进程被污染显存

# ================= 配置区域 =================
LLM_BASE_URL = "http://127.0.0.1:1234/v1"
LLM_API_KEY = "lm-studio"

# 1. 自动指定你想加载的模型名称（必须与 LM Studio 内部列表名称/ID 完全一致）
MODEL_NAME = "Qwen3.5-27B"

BATCH_SIZE = 20             
CONTEXT_SIZE = 3            
MAX_RETRIES = 3             

WHISPER_MODEL_SIZE = "large-v3"
WHISPER_DEVICE = "cuda"
WHISPER_COMPUTE_TYPE = "float16"
WHISPER_DOWNLOAD_ROOT = r"G:\WhisperModels"
WHISPER_LOCAL_ONLY = True   

TOTAL_CORES = multiprocessing.cpu_count()
WHISPER_CPU_THREADS = max(1, TOTAL_CORES - 1) 

SUPPORTED_EXTENSIONS = {
    '.mp4', '.mkv', '.avi', '.mov', '.flv', '.wmv',
    '.wav', '.mp3', '.flac', '.aac', '.m4a', '.ogg','.m4s'
}

# ================= 英语/表音文字 断句参数配置 =================
# ⚠️ 注意：仅对英文等表音文字生效。中文/日文默认使用 Whisper 原生断句。
EN_MAX_CHARS = 70           # 常规换行字符数阈值（达到此长度开始考虑断句）
EN_ABSOLUTE_MAX_CHARS = 90  # 绝对截断红线（防止无限吸附导致字幕溢出屏幕）
EN_MAX_GAP = 0.8            # 单词间最大允许停顿秒数（超过此停顿强制断句）
EN_TOLERANCE_WORDS = 2      # 孤儿词容忍度（如果段落末尾只剩 <=2 个词，触发吸附不断句）
# ============================================================

CLIENT = OpenAI(
    base_url=LLM_BASE_URL, 
    api_key=LLM_API_KEY,
    timeout=None 
)

def get_cleaner_prompt(lang='auto'):
    lang = lang.lower() if lang else 'auto'
    
    if lang == 'ja':
        return """你是一个严谨的日语文本校对专家。你的任务是修复语音识别（ASR）生成的日语字幕中的错别字和语病。
【最高优先级规则】
1. 绝对不要输出任何推理过程！严禁使用 <think> 标签！
2. 绝对不要解释你的修改原因！不要带任何前后缀废话！
3. 只能输出修正后的日语文本，绝对不要翻译成中文！
4. 保持原有格式 [ID: x] 绝对不变！输入多少个 ID，必须输出多少个 ID。
【强制输出示例】
输入:
[ID: 1] 300これが福利の早見表だカイジくん
输出:
[ID: 1] これが複利の早見表だカイジくん
请严格按照上述格式，直接开始输出校对后的日语内容："""

    elif lang == 'en':
        return """You are a rigorous English text proofreading expert. Your task is to fix errors in English subtitles generated by ASR, focusing on homophones, capitalization, and punctuation.
【Priority Rules】
1. NO reasoning process! NO <think> tags!
2. NO explanations! NO prefixes or suffixes!
3. Output ONLY the corrected English text. DO NOT translate!
4. Keep the [ID: x] format EXACTLY as provided.
【Example】
Input:
[ID: 1] their are so many people in the apple store
输出:
[ID: 1] There are so many people in the Apple Store.
Please start outputting the corrected English content directly:"""

    elif lang.startswith('zh'):
        return """你是一个严谨的中文文本校对专家。你的任务是修复语音识别（ASR）生成的中文字幕中的错别字（如标点遗漏、同音字错误）。
【最高优先级规则】
1. 绝对不要输出任何推理过程！严禁使用 <think> 标签！
2. 绝对不要解释你的修改原因！不要带任何前后缀废话！
3. 只能输出修正后的中文文本！
4. 保持原有格式 [ID: x] 绝对不变！输入多少个 ID，必须输出多少个 ID。
【强制输出示例】
输入:
[ID: 1] 戴尔电脑的平幕坏了
输出:
[ID: 1] 戴尔电脑的屏幕坏了
请严格按照上述格式，直接开始输出校对后的中文内容："""

    else:
        return """你是一个严谨的多语言文本校对专家。你的任务是修复语音识别（ASR）生成的字幕中的错别字和语病。
【最高优先级规则】
1. 绝对不要输出任何推理过程！严禁使用 <think> 标签！
2. 绝对不要解释你的修改原因！不要带任何前后缀废话！
3. 只能输出修正后的原文，绝对不要翻译成中文！
4. 保持原有格式 [ID: x] 绝对不变！输入多少个 ID，必须输出多少个 ID。
请严格按照上述格式，直接开始输出校对后的内容："""

def get_translator_prompt(lang='auto'):
    lang = lang.lower() if lang else 'auto'
    
    if lang.startswith('zh'):
        return None
        
    elif lang == 'ja':
        return """你是一名专业的字幕翻译专家。你的任务是将带有 [ID: x] 标签的日语字幕翻译成自然、准确的中文。
【最高优先级规则】
1. 绝对不要输出任何推理过程！严禁使用 <think> 标签！
2. 绝对不要解释你的翻译思路！不要带任何前后缀废话！
3. 保持原有格式 [ID: x] 绝对不变！输入多少个 ID，必须输出多少个 ID。
【强制输出示例】
输入:
[ID: 1] ご飯できたよ。
输出:
[ID: 1] 饭做好了。
请严格按照上述格式，直接开始输出纯中文翻译内容："""

    elif lang == 'en':
        return """你是一名专业的字幕翻译专家。你的任务是将带有 [ID: x] 标签的英语字幕翻译成自然、准确的中文。注意处理英语的俚语和连读误识别。
【最高优先级规则】
1. 绝对不要输出任何推理过程！严禁使用 <think> 标签！
2. 绝对不要解释你的翻译思路！不要带任何前后缀废话！
3. 保持原有格式 [ID: x] 绝对不变！输入多少个 ID，必须输出多少个 ID。
【强制输出示例】
输入:
[ID: 1] This is exactly what I need.
输出:
[ID: 1] 这正是我需要的。
请严格按照上述格式，直接开始输出纯中文翻译内容："""

    else:
        return """你是一名专业的字幕翻译专家。你的任务是将带有 [ID: x] 标签的源语言字幕，准确、流畅地翻译成中文。请根据语境自动判断源语言。
【最高优先级规则】
1. 绝对不要输出任何推理过程！严禁使用 <think> 标签！
2. 绝对不要解释你的翻译思路！不要带任何前后缀废话！
3. 保持原有格式 [ID: x] 绝对不变！输入多少个 ID，必须输出多少个 ID。
请严格按照上述格式，直接开始输出纯中文翻译内容："""

def transcribe_audio(file_path, model):
    print(f"\n🎙️ 正在转录: {file_path.name}")
    
    segments_generator, info = model.transcribe(
        str(file_path), 
        beam_size=5,
        vad_filter=True,                   
        vad_parameters=dict(min_silence_duration_ms=500), 
        condition_on_previous_text=False,
        word_timestamps=True  
    )
    
    lang_code = info.language.lower()
    print(f"🌐 检测到语言: {lang_code} (置信度: {info.language_probability:.2f})")
    print("-" * 50) 
    
    subtitles = []
    seg_id = 1
    
    # ================= 🚀 双引擎路由逻辑 (恢复实时流式输出) =================
    if lang_code.startswith('zh') or lang_code == 'ja':
        print("⏳ 正在提取原声字幕 (路由策略: CJK 原生段落引擎)...") 
        for segment in segments_generator:
            start_time = format_time_srt(segment.start)
            end_time = format_time_srt(segment.end)
            text = segment.text.strip()
            print(f"[{start_time} -> {end_time}] {text}")
            
            subtitles.append({
                'id': str(seg_id),
                'time': f"{start_time} --> {end_time}",
                'text': text,
                'clean_text': '', 
                'translated': ''
            })  
            seg_id += 1
            
    else:
        print("⏳ 正在提取原声字幕 (路由策略: 英语/表音文字 段落级前瞻容忍引擎)...") 
        for segment in segments_generator:
            if segment.words:
                current_words = []
                chunk_start = segment.words[0].start
                
                for i, word_obj in enumerate(segment.words):
                    current_words.append(word_obj.word)
                    
                    is_last_word = (i == len(segment.words) - 1)
                    words_left = len(segment.words) - 1 - i  
                    
                    gap_to_next = 0.0
                    if not is_last_word:
                        gap_to_next = segment.words[i+1].start - word_obj.end
                        
                    current_text = "".join(current_words).strip()
                    must_cut = False
                    
                    if is_last_word:
                        must_cut = True
                    elif len(current_text) >= EN_ABSOLUTE_MAX_CHARS:
                        must_cut = True
                    elif len(current_text) >= EN_MAX_CHARS or gap_to_next >= EN_MAX_GAP:
                        if words_left <= EN_TOLERANCE_WORDS:
                            must_cut = False 
                        else:
                            must_cut = True
                    
                    if must_cut:
                        chunk_end = word_obj.end
                        start_time = format_time_srt(chunk_start)
                        end_time = format_time_srt(chunk_end)
                        
                        print(f"[{start_time} -> {end_time}] {current_text}")
                        
                        subtitles.append({
                            'id': str(seg_id),
                            'time': f"{start_time} --> {end_time}",
                            'text': current_text,
                            'clean_text': '', 
                            'translated': ''
                        })
                        seg_id += 1
                        
                        if not is_last_word:
                            chunk_start = segment.words[i+1].start
                        current_words = []
            else:
                start_time = format_time_srt(segment.start)
                end_time = format_time_srt(segment.end)
                text = segment.text.strip()
                print(f"[{start_time} -> {end_time}] {text}")
                
                subtitles.append({
                    'id': str(seg_id),
                    'time': f"{start_time} --> {end_time}",
                    'text': text,
                    'clean_text': '', 
                    'translated': ''
                })  
                seg_id += 1

    return subtitles, lang_code

def check_llm_ready():
    print(f"\n📡 正在预检 LM Studio 连接及加载模型 ({MODEL_NAME})...")
    try:
        response = CLIENT.chat.completions.create(
            model=MODEL_NAME,
            messages=[{"role": "user", "content": "1+1="}],
            max_tokens=2,
            temperature=0.1
        )
        print("✅ 大模型预检通过，已成功载入显存！")
        return True
    except Exception as e:
        print(f"\n❌ [致命错误] 无法连接到 LM Studio 或模型名称错误！")
        print(f"⚠️ 请检查：\n1. LM Studio Server 是否已启动\n2. MODEL_NAME ('{MODEL_NAME}') 是否与列表里的 Identifier 完全一致！\n详细报错: {e}")
        return False

def ai_clean_batch(batch_subs, context_subs, lang):
    context_text = " ".join([s['clean_text'] or s['text'] for s in context_subs])
    target_ids = [sub['id'] for sub in batch_subs]
    target_text = "\n".join([f"[ID: {sub['id']}] {sub['text']}" for sub in batch_subs])

    user_content = ""
    if context_text:
        user_content += f"【前文语境参考】:\n{context_text}\n\n"
    user_content += f"【待校对的字幕】:\n{target_text}"

    best_cleaned_dict = {}
    
    for attempt in range(MAX_RETRIES):
        try:
            response = CLIENT.chat.completions.create(
                model=MODEL_NAME,
                messages=[
                    {"role": "system", "content": get_cleaner_prompt(lang)},
                    {"role": "user", "content": user_content}
                ],
                temperature=0.3, top_p=0.8, max_tokens=2500,
                extra_body={"chat_template_kwargs": {"enable_thinking": False}}
            )
            
            result_text = response.choices[0].message.content.strip()
            result_text = re.sub(r'<think>.*?</think>', '', result_text, flags=re.DOTALL | re.IGNORECASE).strip()
            
            pattern = r'\[ID:\s*(\d+)\](.*?)(?=\[ID:|\Z)'
            matches = list(re.finditer(pattern, result_text, re.IGNORECASE | re.DOTALL))
            
            for match in matches:
                pid = match.group(1)
                c_text = match.group(2).strip()
                if c_text and pid in target_ids:
                    best_cleaned_dict[pid] = c_text

            if len(best_cleaned_dict) >= len(batch_subs) * 0.8:
                break
                
        except Exception as e:
            print(f"\n⚠️ [警告] 清洗 API 调用失败，正在重试 ({attempt+1}/{MAX_RETRIES})... 异常: {e}")
            time.sleep(3) 
    else:
        print("\n❌ 连续多次调用失败，跳过当前批次清洗！")

    print(f"\n--- 📝 文本清洗对比 (Agent 1 - {lang}) ---")
    for sub in batch_subs:
        if sub['id'] in best_cleaned_dict:
            sub['clean_text'] = best_cleaned_dict[sub['id']]
        else:
            sub['clean_text'] = sub['text'] 
            
        orig = sub['text']
        cleaned = sub['clean_text']
        if orig != cleaned:
            print(f"[ID: {sub['id']}] 🔧 修正: {orig}\n          => {cleaned}")
        else:
            print(f"[ID: {sub['id']}] ✨ 保持: {orig}")
    print("---------------------------------\n")

def translate_batch(batch_subs, context_subs, lang):
    context_text = " ".join([s['translated'] for s in context_subs if s['translated']])
    target_ids = [sub['id'] for sub in batch_subs]
    target_text = "\n".join([f"[ID: {sub['id']}] {sub['clean_text']}" for sub in batch_subs])

    user_content = ""
    if context_text:
        user_content += f"【前文语境参考】:\n{context_text}\n\n"
    user_content += f"【待翻译的字幕】:\n{target_text}"

    best_translated_dict = {}

    for attempt in range(MAX_RETRIES):
        try:
            response = CLIENT.chat.completions.create(
                model=MODEL_NAME,
                messages=[
                    {"role": "system", "content": get_translator_prompt(lang)},
                    {"role": "user", "content": user_content}
                ],
                temperature=0.7, top_p=0.8, max_tokens=2500,
                extra_body={"chat_template_kwargs": {"enable_thinking": False}}
            )
            
            result_text = response.choices[0].message.content.strip()
            result_text = re.sub(r'<think>.*?</think>', '', result_text, flags=re.DOTALL | re.IGNORECASE).strip()
            
            pattern = r'\[ID:\s*(\d+)\](.*?)(?=\[ID:|\Z)'
            matches = list(re.finditer(pattern, result_text, re.IGNORECASE | re.DOTALL))
            
            for match in matches:
                pid = match.group(1)
                trans_text = match.group(2).strip()
                if trans_text and pid in target_ids:
                    best_translated_dict[pid] = trans_text

            if len(best_translated_dict) >= len(batch_subs) * 0.8:
                break
                
        except Exception as e:
            print(f"\n⚠️ [警告] 翻译 API 调用失败，正在重试 ({attempt+1}/{MAX_RETRIES})... 异常: {e}")
            time.sleep(3) 
    else:
        print("\n❌ 连续多次调用失败，跳过当前批次翻译！")

    missing_ids = [sub['id'] for sub in batch_subs if sub['id'] not in best_translated_dict]
    if missing_ids:
        base_context_list = [s['translated'] for s in context_subs if s['translated']]
        for missing_id in missing_ids:
            current_index = next((i for i, sub in enumerate(batch_subs) if sub['id'] == missing_id), -1)
            if current_index == -1: continue
            orig_text = batch_subs[current_index]['clean_text']
            
            current_batch_context = [best_translated_dict[batch_subs[i]['id']] for i in range(current_index) if batch_subs[i]['id'] in best_translated_dict]
            full_context_list = base_context_list + current_batch_context
            dynamic_context_str = " ".join(full_context_list[-CONTEXT_SIZE:])
            
            sys_prompt = "你是一个专业的字幕翻译。请把待翻译的源语言文本直接翻译成中文。只输出中文，严禁解释，严禁使用<think>标签。"
            rescue_prompt = f"【前文语境】:\n{dynamic_context_str}\n\n【待翻译文本】:\n{orig_text}"
            
            try:
                resp = CLIENT.chat.completions.create(
                    model=MODEL_NAME,
                    messages=[{"role": "system", "content": sys_prompt}, {"role": "user", "content": rescue_prompt}],
                    temperature=0.2, max_tokens=300 
                )
                rescue_text = resp.choices[0].message.content.strip()
                rescue_text = re.sub(r'<think>.*?</think>', '', rescue_text, flags=re.DOTALL | re.IGNORECASE).strip()
                rescue_text = re.sub(r'^(好的|翻译|中文|如下|翻译结果)[:：，。\s]*', '', rescue_text, flags=re.IGNORECASE).strip()
                if rescue_text: best_translated_dict[missing_id] = rescue_text
            except: pass

    print(f"\n--- 翻译进度流 (Agent 2 - {lang}) ---")
    for sub in batch_subs:
        trans_text = best_translated_dict.get(sub['id'])
        if trans_text:
            sub['translated'] = trans_text
            print(f"[ID: {sub['id']}] {trans_text}")
        else:
            sub['translated'] = sub['clean_text']
            print(f"[ID: {sub['id']}] (⚠️保留原文) {sub['clean_text']}")
    print("----------------------------\n")

def get_ass_header(is_chinese_only=False):
    base_header = "[Script Info]\nTitle: Subtitles\nScriptType: v4.00+\nWrapStyle: 0\nScaledBorderAndShadow: yes\nYCbCr Matrix: TV.601\nPlayResX: 3840\nPlayResY: 2160\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\nStyle: 黑体-蓝,黑体,120,&H00FFFFFF,&HFFFFFFFF,&H00734111,&H00FFFFFF,-1,0,0,0,100,100,0,0,1,5,0,2,10,10,80,1\n"
    en_style = "Style: EN,微软雅黑,100,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,3,0.5,2,10,10,20,1\n"
    events_header = "\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    return base_header + events_header if is_chinese_only else base_header + en_style + events_header

def format_time_srt(seconds):
    hours = math.floor(seconds / 3600)
    seconds %= 3600
    minutes = math.floor(seconds / 60)
    seconds %= 60
    milliseconds = round((seconds - math.floor(seconds)) * 1000)
    return f"{hours:02d}:{minutes:02d}:{math.floor(seconds):02d},{milliseconds:03d}"

def srt_time_to_ass(time_str):
    start_str, end_str = time_str.split('-->')
    def convert(t):
        parts = t.strip().replace(',', ':').split(':')
        return f"{int(parts[0])}:{parts[1]}:{parts[2]}.{parts[3][:2]}"
    return convert(start_str), convert(end_str)

def clean_subtitles(subtitles):
    if not subtitles: return [], 0
    cleaned, hallucination_count = [], 0
    WINDOW_SIZE, MAX_OCCURRENCE = 10, 2 
    for sub in subtitles:
        current_text = sub['text'].strip()
        recent_texts = [s['text'].strip() for s in cleaned[-WINDOW_SIZE:]]
        if recent_texts.count(current_text) >= MAX_OCCURRENCE:
            hallucination_count += 1
        else:
            cleaned.append(sub)
    for i, sub in enumerate(cleaned): sub['id'] = str(i + 1)
    return cleaned, hallucination_count

def parse_srt_file(srt_path):
    subtitles = []
    try:
        with open(srt_path, 'r', encoding='utf-8') as f: content = f.read().strip()
    except Exception as e:
        print(f"❌ 无法读取字幕文件 {srt_path.name}: {e}")
        return subtitles
    blocks = re.split(r'\n\n+', content)
    for block in blocks:
        lines = block.strip().split('\n')
        if len(lines) >= 3:
            subtitles.append({
                'id': lines[0].strip(),
                'time': lines[1].strip(),
                'text': " ".join([line.strip() for line in lines[2:]]),
                'clean_text': " ".join([line.strip() for line in lines[2:]]),
                'translated': ''
            })
    return subtitles

def save_srt_file(subtitles, srt_path):
    with open(srt_path, 'w', encoding='utf-8') as f:
        for sub in subtitles:
            out_text = sub.get('clean_text') or sub['text']
            f.write(f"{sub['id']}\n{sub['time']}\n{out_text}\n\n")

def save_ass_file(subtitles, ass_path, is_chinese_only=False):
    with open(ass_path, 'w', encoding='utf-8-sig') as f: 
        f.write(get_ass_header(is_chinese_only))
        for sub in subtitles:
            start_ass, end_ass = srt_time_to_ass(sub['time'])
            orig_text = (sub.get('clean_text') or sub['text']).replace('\n', '\\N')
            if is_chinese_only:
                f.write(f"Dialogue: 0,{start_ass},{end_ass},黑体-蓝,,0,0,0,,{orig_text}\n")
            else:
                trans_text = sub['translated'] if sub['translated'] else orig_text
                trans_text = trans_text.replace('\n', '\\N')
                f.write(f"Dialogue: 0,{start_ass},{end_ass},EN,,0,0,0,,{orig_text}\n")
                f.write(f"Dialogue: 0,{start_ass},{end_ass},黑体-蓝,,0,0,0,,{trans_text}\n")

def extract_and_sanitize_audio(file_path):
    if not shutil.which("ffmpeg"): return file_path, False
    temp_wav_path = file_path.with_name(f"{file_path.stem}_temp_sanitized.wav")
    print(f"🎛️ 正在净化重采样音轨: {file_path.name}")
    command = ["ffmpeg", "-y", "-i", str(file_path), "-vn", "-c:a", "pcm_s16le", "-ar", "16000", "-ac", "1", "-af", "aresample=async=1", str(temp_wav_path)]
    try:
        subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        return temp_wav_path, True
    except subprocess.CalledProcessError:
        if temp_wav_path.exists():
            try: temp_wav_path.unlink()
            except: pass
        return file_path, False

def unload_llm(model_name):
    print(f"\n🗑️ [内存管理] 正在请求 LM Studio 卸载大模型...")
    try:
        get_resp = httpx.get(f"{LLM_BASE_URL}/models", timeout=5)
        if get_resp.status_code == 200:
            models_data = get_resp.json().get("data", [])
            
            if not models_data:
                print("✅ LM Studio 报告当前显存中没有加载任何模型。")
                return
                
            target_instance_id = None
            for m in models_data:
                actual_id = m.get("id", "")
                if actual_id.lower() == model_name.lower():
                    target_instance_id = actual_id
                    break
            
            if not target_instance_id and len(models_data) > 0:
                target_instance_id = models_data[0].get("id")
                print(f"⚠️ 未找到完全匹配的 '{model_name}'，但检测到占用显存的实例 '{target_instance_id}'。")

            if target_instance_id:
                print(f"📡 锁定目标实例 ID: {target_instance_id}，正在发送卸载指令...")
                unload_url = "http://127.0.0.1:1234/api/v1/models/unload"
                payload = {"instance_id": target_instance_id}
                
                unload_resp = httpx.post(unload_url, json=payload, timeout=5)
                try:
                    resp_json = unload_resp.json()
                except:
                    resp_json = {}

                if unload_resp.status_code == 200 and "error" not in resp_json:
                    print(f"✅ 大模型 [{target_instance_id}] 已成功从 LM Studio 卸载，显存已清空。")
                else:
                    print(f"⚠️ 卸载可能未完全成功，服务器返回: {resp_json}")
        else:
            print(f"⚠️ 无法获取当前模型状态，API 返回码: {get_resp.status_code}")
            
    except Exception as e:
        print(f"⚠️ 自动卸载请求失败 (连接异常): {e}\n请在 LM Studio 界面手动点击 Eject 释放显存。")

# ================= 阶段分离执行逻辑 =================

def phase_1_transcribe(file_path, whisper_model, mode):
    base_name = file_path.with_suffix('')
    srt_path = Path(f"{base_name}.srt")
    ass_path = Path(f"{base_name}.ass")
    lang_path = file_path.with_suffix('.lang')

    if mode == '1' and srt_path.exists() and ass_path.exists():
        print(f"⏭️ 目标双语字幕已存在，跳过听写: {file_path.name}")
        return True
    elif mode == '2' and srt_path.exists():
        print(f"⏭️ SRT 存在，跳过听写: {file_path.name}")
        return True

    audio_target, is_temp = extract_and_sanitize_audio(file_path)
    try:
        raw_subtitles, language = transcribe_audio(audio_target, whisper_model)
    finally:
        if is_temp and audio_target.exists():
            try: audio_target.unlink()
            except: pass

    if not raw_subtitles: return False
        
    cleaned_subtitles, hall_count = clean_subtitles(raw_subtitles)
    print(f"🧹 基础清洗完毕: 拦截 {hall_count} 处幻觉。")

    save_srt_file(cleaned_subtitles, srt_path)

    with open(lang_path, 'w', encoding='utf-8') as f:
        f.write(language)

    is_chinese = language.lower().startswith('zh')
    if is_chinese and mode == '1':
        save_ass_file(cleaned_subtitles, ass_path, is_chinese_only=True)
        print("✅ 检测为中文，已直出 ASS。")
        if lang_path.exists():
            try: lang_path.unlink()
            except: pass
        
    return True

def run_whisper_process(media_files_str, mode):
    try:
        from faster_whisper import WhisperModel
        print("⏳ [独立子进程] 正在挂载 Whisper 模型至显存...")
        whisper_model = WhisperModel(WHISPER_MODEL_SIZE, device=WHISPER_DEVICE, compute_type=WHISPER_COMPUTE_TYPE, download_root=WHISPER_DOWNLOAD_ROOT, cpu_threads=WHISPER_CPU_THREADS, local_files_only=WHISPER_LOCAL_ONLY)
        
        media_files = [Path(p) for p in media_files_str]
        for file_path in media_files:
            phase_1_transcribe(file_path, whisper_model, mode)
            
        print("\n🗑️ [内存管理] 阶段 1 任务完成。即刻自我销毁以交还操作系统显存...")
    except Exception as e:
        print(f"\n❌ [子进程致命错误] {e}")
        traceback.print_exc()
    finally:
        os._exit(0)

def phase_2_llm_process(file_path, mode):
    base_name = file_path.with_suffix('')
    srt_path = file_path if mode == '3' else Path(f"{base_name}.srt")
    ass_path = Path(f"{base_name}.ass")
    lang_path = file_path.with_suffix('.lang')

    print(f"\n📄 正在解析字幕准备大模型处理: {srt_path.name}")
    cleaned_subtitles = parse_srt_file(srt_path)
    if not cleaned_subtitles: 
        print(f"⚠️ 读取的 SRT 格式不合法或内容为空，跳过处理。")
        return
        
    cleaned_lines = len(cleaned_subtitles)

    lang = 'auto'
    if lang_path.exists():
        with open(lang_path, 'r', encoding='utf-8') as f:
            lang = f.read().strip()

    if lang.startswith('zh') or lang == 'ja':
        print(f"\n🛠️ 启动 Agent 1 (文本校对): 使用 {MODEL_NAME}，当前语言策略: {lang}")
        for i in range(0, cleaned_lines, BATCH_SIZE):
            batch = cleaned_subtitles[i : i + BATCH_SIZE]
            context = cleaned_subtitles[max(0, i - CONTEXT_SIZE) : i]
            print(f"⏳ 正在校对批次: {i+1} - {min(i + BATCH_SIZE, cleaned_lines)} / {cleaned_lines} 行")
            ai_clean_batch(batch, context, lang)
    else:
        print(f"\n⏭️ 检测为 {lang} 语种，跳过 Agent 1 (文本校对)，保留 Whisper 原声高精度字幕...")
        for sub in cleaned_subtitles:
            sub['clean_text'] = sub['text']

    save_srt_file(cleaned_subtitles, srt_path)

    trans_prompt = get_translator_prompt(lang)
    if trans_prompt is None:
        print(f"\n⏭️ 检测为中文体系 ({lang})，跳过 Agent 2 翻译环节，直接生成单语 ASS 字幕...")
        save_ass_file(cleaned_subtitles, ass_path, is_chinese_only=True)
        
        if lang_path.exists():
            try: lang_path.unlink()
            except: pass
            
        print(f"✅ {file_path.name} 单体流水线执行完毕！")
        return

    print(f"\n🚀 启动 Agent 2 (跨语言翻译): 继续使用 {MODEL_NAME}")
    for i in range(0, cleaned_lines, BATCH_SIZE):
        batch = cleaned_subtitles[i : i + BATCH_SIZE]
        context = cleaned_subtitles[max(0, i - CONTEXT_SIZE) : i]
        print(f"⏳ 正在翻译批次: {i+1} - {min(i + BATCH_SIZE, cleaned_lines)} / {cleaned_lines} 行")
        translate_batch(batch, context, lang)
        save_ass_file(cleaned_subtitles, ass_path, is_chinese_only=False)

    if lang_path.exists():
        try: lang_path.unlink()
        except: pass
        
    print(f"✅ {file_path.name} 单体流水线执行完毕！")

def run_pipeline():
    print("╔══════════════════════════════════════════╗")
    print("║ 大模型单体双 Agent 字幕流水线             ║")
    print("╚══════════════════════════════════════════╝")
    mode = input("👉 请输入模式编号 (1/听译全流 2/仅听写 3/仅翻译): ").strip() or '1'
    
    # 支持拖入文件或文件夹
    target_input = input("📁 请拖入目标文件或文件夹路径: ").strip().strip('"').strip("'")
    target_path = Path(target_input)

    if not target_path.exists(): 
        print("❌ 路径不存在！")
        return

    media_files = []
    if target_path.is_file():
        if (mode in ['1', '2'] and target_path.suffix.lower() in SUPPORTED_EXTENSIONS) or \
           (mode == '3' and target_path.suffix.lower() == '.srt'):
            media_files.append(target_path)
        else:
            print(f"❌ 不支持的文件格式或当前模式不匹配: {target_path.name}")
            return
    elif target_path.is_dir():
        recursive = input("🗂️ 扫描子目录？(y/N): ").strip().lower() == 'y'
        media_files = [f for f in (target_path.rglob('*') if recursive else target_path.glob('*')) 
                       if f.is_file() and ((mode in ['1','2'] and f.suffix.lower() in SUPPORTED_EXTENSIONS) or 
                                           (mode == '3' and f.suffix.lower() == '.srt'))]

    if not media_files: 
        print("❌ 在该路径下没有找到可处理的文件。")
        return
        
    print(f"🎯 共发现 {len(media_files)} 个初始任务。")
    
    # 记录总任务开始时间
    pipeline_start_time = time.time()

    # ================= 阶段 1 (物理隔离) =================
    if mode in ['1', '2']:
        print("\n" + "="*50)
        print("▶️ [阶段 1] 开始全局批量语音识别 (启动物理隔离子进程)...")
        print("="*50)
        
        media_files_str = [str(f) for f in media_files]
        p = multiprocessing.Process(target=run_whisper_process, args=(media_files_str, mode))
        p.start()
        p.join() 

        print("✅ [系统回收] Whisper 子进程已物理销毁，Windows 操作系统已 100% 回收显存。")
    
    # ================= 阶段 2 =================
    if mode in ['1', '3']:
        files_for_llm = []
        if mode == '1':
            for file_path in media_files:
                base_name = file_path.with_suffix('')
                srt_path = Path(f"{base_name}.srt")
                ass_path = Path(f"{base_name}.ass")
                if srt_path.exists() and not ass_path.exists():
                    files_for_llm.append(file_path)
        elif mode == '3':
            files_for_llm = media_files

        if files_for_llm:
            print("\n" + "="*50)
            print(f"▶️ [阶段 2] 开始全局大模型文本校对与翻译 (待处理文件: {len(files_for_llm)}个)")
            print("="*50)
            
            if not check_llm_ready():
                return

            for file_path in files_for_llm:
                phase_2_llm_process(file_path, mode)
                
            unload_llm(MODEL_NAME)
        else:
            print("\n⚠️ 阶段二被跳过：所有文件皆已被识别为中文或历史 ASS 已存在。")

    # 结算总耗时
    total_time = time.time() - pipeline_start_time
    hours, rem = divmod(total_time, 3600)
    minutes, seconds = divmod(rem, 60)
    
    print("\n" + "🎉" * 20)
    print(f"✅ 所有任务流水线已全部完成！")
    print(f"⏱️ 任务总耗时: {int(hours)}小时 {int(minutes)}分钟 {seconds:.2f}秒")
    print("🎉" * 20)

# ================= 强制阻塞外壳 =================
if __name__ == "__main__":
    multiprocessing.freeze_support()
    try:
        run_pipeline()
    except KeyboardInterrupt:
        print("\n\n🛑 接收到强制中断信号 (Ctrl+C)，正在终止程序...")
        unload_llm(MODEL_NAME)
    except Exception as e:
        print("\n\n❌ 程序遭遇未捕获的致命错误，堆栈追踪如下：")
        traceback.print_exc()
    finally:
        gc.collect()
        print("\n" + "═" * 50)
        if os.name == 'nt':
            os.system('pause')
        else:
            input("按回车键退出程序...")